app:
HOST_IP: 127.0.0.1
ENV: debugging
APP_PORT: 8080
APPLY_MIGRATION: true
ACCESS_TOKEN_EXP: 15
REFRESH_TOKEN_EXP: 168
JWT_SECRET: SAMPLE
DB_TYPE: postgres

postgres:
DB_HOST: 127.0.0.1
DB_USER: alibagheri
DB_PASSWORD: Abcd1234
DB_NAME: mysql
DB_PORT: 3306
